### ISSUE TITLE
nonoptimal solution on nlp

### ISSUE THREAD

**Issue by svigerske** [svigerske/gamsworhp#4]
Running the NLP
```
Variables  x1,x2,x3,x4,x5,x6,x7;
Positive Variables  x5,x6;
Equations  e1,e2,e3,e4,e5,e6;

e1..  - 2*x1 + x4 =E= 0;
e2..    x5 + x6 =L= 7;
e3.. -(sqr(x2) + sin(0.1*x3)) - 2*x1 - 5*x5 + x7 =E= 0;
e4.. x2**1.5 + x6 =L= 3;
e5.. -log(x1) - x3 =G= -1;
e6.. x4**1.1 - x6 =E= 0;

* set non-default bounds
x1.lo = 0.1; x1.up = 2;
x2.lo = 0.001; x2.up = 3;
x3.lo = 0.001; x3.up = 4;
x4.lo = 0.001; x4.up = 1;
x5.up = 10;
x6.up = 10;

* set non-default levels
x1.l = 0.1;
x2.l = 0.001;
x3.l = 0.001;
x4.l = 0.001;

Model m / all /;

m.limrow=0; m.limcol=0;

option nlp = worhp;
Solve m using NLP maximizing x7;

option nlp = examiner2;
Solve m using NLP maximizing x7;
```
shows that Worhp stopped in a solution that is not locally optimal, as complementarity slackness is violated for the bound constraint on x2:
```
...
 Final values after iteration 29:
 Final objective value ............. -3.4677944966E+01
 Final constraint violation ........  0.0000000000E+00
 Final KKT conditions ..............  3.5051480152E-08
 Successful termination: Optimal Solution Found.
--- Restarting execution
--- gams.gms(58) 2 Mb
--- Reading solution for model m
--- gams.gms(60) 2 Mb
--- Generating NLP model m
--- gams.gms(61) 4 Mb
---   6 rows  7 columns  15 non-zeroes
---   25 nl-code  5 nl-non-zeroes
--- gams.gms(61) 2 Mb
--- Executing EXAMINER2: elapsed 0:00:00.021

EXAMINER UTIL    24.8.2 r59988 Released Jan  3, 2017 LEG x86 64bit/Linux      


No actions were specified: defaulting to 'ExamineInitPoint yes'
To choose a different action, use an option file

InitPoint - GAMS-provided x.l & f.m, Examiner-computed x.m & f.s:
Scale range (observed but not applied): [1,10]
Maximum element: row=e5, col=x1: Aij = 10
Primal variable bounds satisfied (tol = 1e-06)
Dual variable bounds satisfied (tol = 1e-06)
Primal constraints satisfied (tol = 1e-06)
Dual constraints satisfied (tol = 1e-06)
Primal CS is nonzero (tol = 1e-07):
  Max violation: x2.l: 0.001 <= 0.0706917 <= 3
                 x2.m: -INF <= 0.141383 <= +INF
Dual CS is zero (tol = 1e-07)

EXAMINER ALL DONE.
```
If I change the NLP solver to CONOPT, it looks better:
```
...
   Iter Phase Ninf     Objective     RGmax    NSB   Step InItr MX OK
      6   3        3.8675408373E+01 2.0E+01     3 1.0E+00    3 T  T
      8   3        3.8675408371E+01 0.0E+00     0
 
 ** Optimal solution. There are no superbasic variables.
 
--- Restarting execution
--- gams.gms(58) 2 Mb
--- Reading solution for model m
--- gams.gms(60) 2 Mb
--- Generating NLP model m
--- gams.gms(61) 4 Mb
---   6 rows  7 columns  15 non-zeroes
---   25 nl-code  5 nl-non-zeroes
--- gams.gms(61) 2 Mb
--- Executing EXAMINER2: elapsed 0:00:00.018

EXAMINER UTIL    24.8.2 r59988 Released Jan  3, 2017 LEG x86 64bit/Linux      


No actions were specified: defaulting to 'ExamineInitPoint yes'
To choose a different action, use an option file

InitPoint - GAMS-provided x.l & f.m, Examiner-computed x.m & f.s:
Scale range (observed but not applied): [1,10]
Maximum element: row=e5, col=x1: Aij = 10
Primal variable bounds satisfied (tol = 1e-06)
Dual variable bounds satisfied (tol = 1e-06)
Primal constraints satisfied (tol = 1e-06)
Dual constraints satisfied (tol = 1e-06)
Primal CS is zero (tol = 1e-07)
Dual CS is zero (tol = 1e-07)

EXAMINER ALL DONE.
```

**Comment by renkekuhlmann** [comment]
Which gams model is this?

**Comment by svigerske** [comment]
It comes from GAMS testlib NLP01 (http://www.gams.com/latest/testlib_ml/libhtml/testlib_nlp01.html).
I thought I might try NLPs for a change. :)

**Comment by renkekuhlmann** [comment]
Checked that when entering the problem directly in WORHP the correct solution and marginals are calculated. So, there must be something in the interface that leads to false interpretation of the NLP...

**Comment by svigerske** [comment]
Hmm, I didn't look deep into your interface code. Scimming through, what about this line in UserDG:
```
      for ( ; k < (*DGrowStartInit)[i+1]; ++k)
      {
         (*DGvalInit)[k] = (*DGvalDenseInit)[(*DGcolInit)[k]];
      }
```
Does (*DGcolInit)[k] need to be decreased by 1 by coincidence?

Do you have some kind of derivative checker in WORHP, which you could enable?
Or does it converge better if you enable finite differences for derivatives?

**Comment by renkekuhlmann** [comment]
I am just checking this. Had the same idea. Seems that there is a problem with the hessian matrix.

**Comment by renkekuhlmann** [comment]
The problem with the Hessian matrix did not solve the issue. However, I found a problem with the gradient of the objective. I use 'gmoGetObjSparse' to get it. It returns Dobj / Du = 2e-3 constantly in every iteration, but I expect 2 * u. Maybe there is something wrong with the function call I do.

Edit: u = x2 in the above description.

**Comment by renkekuhlmann** [comment]
I switched to the dense function and it works now. However I still have problems with NLP01 in the case that the objective function is scaled, e.g. cz = 0.5. How can I get this scaling value to rescale the objective function after the solve?

**Comment by renkekuhlmann** [comment]
Ah, misunderstood the test. One dual cannot be solved up to a tolerance of 1e-6 but 1e-5. If TolOpti of WORHP is set to 1e-7 the test can be solved without problems.

**Comment by svigerske** [comment]
Thanks for the fixes. I'll look into the problem with the sparse objective later.

**Comment by svigerske** [comment]
I think gmoGetObjSparse() is not meant to get the objective gradient for a nonlinear objective during optimization. You cannot pass it the current point (opt->X) where to evaluate the objective.
So gmoGetObjSparse() probably gives you always the gradient w.r.t. the starting point in GAMS, i.e., from the point when the model is instantiated.
So, gmoGetObjSparse() is useful to get the coefficients for the linear part of the objective, to see which variables appear, and whether they do so in linear or nonlinear form.

Using gmoEvalGradObj() is the right way to get the gradient of the objective at a particular point. It works analogously to gmoEvalGrad() for gradients of constraints.
